version: '3.1'
services:
  mysql-ci-cd:
    image: mysql:8.0
    container_name: container_mysql-ci-cd
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ci-cd_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD

  phpmyadmin-ci-cd:
    container_name: container_phpmyadmin-ci-cd
    image: phpmyadmin/phpmyadmin
    ports:
      - '8085:80'
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: mysql-cicd-db
      PMA_USER: user
      PMA_PASSWORD: user
    depends_on:
      - mysql-ci-cd
    restart: unless-stopped
volumes:
  mysql_data:
    driver: local


